subPackages:
  - build

docker:
  build:
    defaultTag: latest
    autoTags: [main, latest, next]

docs:
  location: docs

  aliases:
    /api: https://raw.githubusercontent.com/softvisio-node/core/main/docs/api.md

  app:
    rpc:
      url: ws://datasets/api
